### ISSUE TITLE
tag view is not very nice visually

### ISSUE THREAD

**Issue by arthurlutz** [katel/omeka-foundation#2]
A quick tweaking in firebug enhances the view : 
- remove 50% on hTagcloud ul { width: 50%; }
- remove margin from hTagcloud li {         /_margin: 0 20px 20px 0;_/ }

But maybe there is a better way or a good reason to keep that.

**Comment by katel** [comment]
This is a starter theme for people to be able to use to create their own using the Foundation framework. The styles are very barebones for this reason. Some of the styles could definitely use some tidying up so will look into it but the aesthetics are secondary to making it easy to create new themes from and showing how foundation CSS works.
