### ISSUE TITLE
2.0 Compat

### ISSUE THREAD

**Issue by drewrowland** [katel/omeka-foundation#7]
Are you going to update your theme for Omeka 2.0?

**Comment by drewrowland** [comment]
Still showing not ready for 2.0: http://omeka.org/add-ons/themes/omeka-foundation/

**Comment by katel** [comment]
The theme has been updated for Omeka 2 -- will upload the latest version on the Omeka.org site but, in the meantime, you can download it directly from github.

**Comment by katel** [comment]
Now updated on Omeka.org as well. Apologies for the delay.
